s="Tops Technologies"

print(s.capitalize())
print(s.casefold())
print(s.lower())
print(s.upper())
print(s.center(40,"*"))
print(s.count("log"))
print(s.endswith("es"))
print(s.startswith("To"))
print(s.find("log"))
print(s.index("T",3))
print("tops123".isalnum())
print("123".isalnum())
print("tops".isalnum())
print("tops".isalpha())
print("123".isnumeric())
print(" ".isspace())
print(s.istitle())
print(s.swapcase())
print("Hello".replace("l","w"))
print("tops".islower())
print("TOPS".isupper())
